### ISSUE TITLE
Blog article Direct access

### ISSUE THREAD

**Issue by jonathanR79** [stormcloud266/gatsby-photography#1]
Hi,
When accessing a blog article in direct, there are some display issue like if you miss some ressources loading:

E.g:

https://shuttered-photography.netlify.app/blog/grilled-cheese

![image](https://user-images.githubusercontent.com/23026548/94806612-8ac1f980-03ee-11eb-90a1-48c4cdeafa74.png)

**Comment by stormcloud266** [comment]
Thanks for pointing that out! Looks like I missed the Layout component in the template page.

**Comment by jonathanR79** [comment]
Thanks you for this. I really like this clean dark portfolio.

**Comment by stormcloud266** [comment]
Absolutely! Thank you. I'll be pushing an update later today with a fix.

**Comment by jonathanR79** [comment]
Solved. Thanks
